SECRET_KEY: 'godq'
data_store_type: 'mongo'

port: 5000

#es_hosts: ["127.0.0.1:9200"]
mongo_url: 'mongodb://127.0.0.1:27017'
mongo_db: 'test-mgmt'

users:
  - name: 'admin'
    password: 'password'
    role: 'admin'
  - name: 'dev'
    password: 'password'
    role: 'developer'
  - name: 'qe'
    password: 'password'
    role: 'developer'
  - name: 'viewer'
    password: 'password'
    role: 'viewer'
